grails-app/domain/com/mbds/grails/Annonce.groovy
package com.mbds.grails

class Annonce {

    String title
    String description
    Double price

    Date dateCreated
    Date lastUpdated

    static hasMany = [illustrations: Illustration]

    static belongsTo = [author: User]

    static constraints = {
        title       nullable: false, blank: false
        description nullable: false, blank: false
        price       min: 0D
    }

    static mapping = {
        description type: 'text'
    }
}

grails-app/controllers/com/mbds/grails/AnnonceController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.util.Holders
import org.grails.datastore.mapping.validation.ValidationException

import static org.springframework.http.HttpStatus.*

class AnnonceController {

    AnnonceService annonceService
    MyService myService
    UserService userService

    @Secured(['ROLE_ADMIN','ROLE_MODO'])
    def index(Integer max) {
        params.max = Math.min(max ?: 5, 100)
        def title  = params.title
        def price = params.price

        def listAnnonce = myService.listAnnonce(title,price,params)
        def countListAnnonce = myService.countListAnnonce(title,price)

        respond listAnnonce, model:[nbIllustrationAffiche: 4,listMax: myService.listMax(),max: params.max, countList: countListAnnonce, title: params.title, price: params.price]
    }

    @Secured(['ROLE_ADMIN','ROLE_MODO'])
    def show(Long id) {
        respond annonceService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def create() {
        respond new Annonce(params)
    }

    @Secured('ROLE_ADMIN')
    def save(Annonce annonce) {
        if (annonce == null) {
            notFound()
            return
        }

        try {

            def springSecurityService = Holders.applicationContext.springSecurityService
            def user = springSecurityService.currentUser
            //println user.id
            annonce.author = user

            //illustration
            def f = request.getFile("imageupload")
            if (!f.empty) {
                def fileName = f.originalFilename

               def chemin = grailsApplication.config.annonces.illustrations.path+'/'+annonce.title+'.jpg'
                def img=annonce.title+'.jpg'

                f.transferTo(new File(chemin))
                annonce.addToIllustrations(new Illustration(filename: "$img"))
            }
            annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*' { respond annonce, [status: CREATED] }
        }
    }

    @Secured(['ROLE_ADMIN','ROLE_MODO'])
    def edit(Long id) {
        respond annonceService.get(id), model: [userList: User.list(), baseUrl: grailsApplication.config.annonces.illustrations.url]
    }

    @Secured(['ROLE_ADMIN','ROLE_MODO'])
    def update() {
        def annonce = Annonce.get(params.id)
        annonce.title = params.title
        annonce.description = params.description
        annonce.price = Double.parseDouble(params.price)
        if (annonce == null) {
            notFound()
            return
        }
        try {
                    def f = request.getFile("file")
                    if (!f.empty) {
                        def chemin = grailsApplication.config.annonces.illustrations.path + '/' + annonce.title + '.jpg'
                        def img = annonce.title + '.jpg'
                        f.transferTo(new File(chemin))
                        annonce.addToIllustrations(new Illustration(filename: "$img"))
                    }
                    annonce.title = params.title
                    annonce.description = params.description
                    annonce.price = Float.parseFloat(params.price)

                    annonceService.save(annonce)
        } catch (ValidationException e) {
            respond annonce.errors, view:'edit'
            return
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'annonce.label', default: 'Annonce'), annonce.id])
                redirect annonce
            }
            '*'{ respond annonce, [status: OK] }
        }
    }


    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        try{
            annonceService.delete(id)
            render ("success")
        }
        catch(ValidationException e){
            render('echec')
        }


        /* request.withFormat {
             form multipartForm {
                 flash.message = message(code: 'default.deleted.message', args: [message(code: 'annonce.label', default: 'Annonce'), id])
                 redirect action:"index", method:"GET"
             }
             '*'{ render status: NO_CONTENT }
         }*/
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'annonce.label', default: 'Annonce'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*


class UserController {

    UserService userService
    UserRoleService userRoleService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model: [userCount: userService.count(), username: params.username]
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def show(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def create() {
        respond new User(params)
    }

    @Secured('ROLE_ADMIN')
    def save(User user) {
        if (user == null) {
            notFound()
            return
        }
        println "FOUN"
        try {
            userService.save(user)
        } catch (ValidationException e) {
            println "ERROR FIELD"
            respond user.errors, view: 'create'
            return
        }
        println "ERROR"
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def edit(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        try {
            def user = User.findById(id)
            if (user) {
                println user.username

                def delete = UserRole.removeAll(user)
                println delete
                if (delete != 0) {
                    userService.delete(id)
                }
            }
            render("success")
        }
        catch (ValidationException e) {
            render('echec')
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def register() {

        if (!params.password.equals(params.repassword)) {
            flash.message = "Le mot de passe et la confirmation mot de passe ne correspondent pas"
            if (params.id) {
                redirect(action: "edit", id: params.id)
            } else {
                redirect action: "create"
            }

            return
        } else {
            try {
                def user = null
                def role = null
                if (!params.id) {
                        user = new User(username: params.username, password: params.password)
                        userService.save(user)
                    role = Role.get(params.role.id)
                } else {
                    user = userService.get(params.id)
                    println user.username
                    user.username = params.username
                    user.password = params.password
                    role = Role.get(params.role.id)

                }

                if (user && role) {
                    if (!params.id) {
                        UserRole.create user, role
                    } else {
                        userService.save(user)
                        UserRole.removeAll(user)
                        UserRole.create user, role
                    }


                    UserRole.withSession {
                        it.flush()
                        it.clear()
                    }

                    flash.message = "Utilisateur enregistré avec succès."
                    redirect controller: "user", action: "index"
                } else {
                    flash.message = "Veuillez vérifier les champs"
                    if (params.id) {
                        redirect(action: "edit", id: params.id)
                    } else {
                        redirect action: "create"
                    }
                    return
                }
            } catch (ValidationException e) {
                flash.message = "Une erreur s'est produite"
                if (params.id) {
                    redirect(action: "edit", id: params.id)
                } else {
                    redirect action: "create"
                }
                return
            }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/annonce/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <h5 class="card-title text-center"><g:message code="default.create.label" args="[entityName]" /></h5>
                    <g:if test="${flash.message}">
                        <div class="message" role="status">${flash.message}</div>
                    </g:if>
                    <g:hasErrors bean="${this.annonce}">
                        <div class="col-lg-12 mb-4">
                            <div class="card bg-danger text-white shadow">
                                <div class="card-body text-white-50 small">
                                    <g:eachError bean="${this.annonce}" var="error">
                                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                                    </g:eachError>
                                </div>
                            </div>
                        </div>
                    </g:hasErrors>
                    <g:uploadForm controller="annonce" action="save" method="POST" enctype="multipart/form-data">

                            <div class="form-group">
                                <label for="title">Titre</label>
                                <input type="text" placeholder="Titre de l'annonce" class="form-control" name="title" id="title" autocapitalize="none" required/>
                            </div>

                            <div class="form-group">
                                <label for="description">Description</label>
                                <input type="text" placeholder="Description de l'annonce" class="form-control" name="description" id="description" required/>
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="number" placeholder="Prix de l'annonce" class="form-control" name="price" id="price" min="50" required/>
                            </div>
                            <div class="form-group">
                                <label for="imageupload">Add illustration</label>
                                <fieldset class="form">
                                    <input type="file" name="imageupload" id="imageupload"/>
                                </fieldset>
                            </div>

                            <button id="submit" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Enregistrer</button>
                            <hr class="my-4">
                    </g:uploadForm>


                </div>
            </div>
        </div>
    </div>
    </body>
</html>

grails-app/views/annonce/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
    <style>
    * {box-sizing: border-box;}
    body {font-family: Verdana, sans-serif;}
    .mySlides {display: none;}
    img {vertical-align: middle;}

    /* Slideshow container */
    .slideshow-container {
        max-width: 1000px;
        position: relative;
        margin: auto;
    }

    /* Caption text */
    .text {
        color: #f2f2f2;
        font-size: 15px;
        padding: 8px 12px;
        position: absolute;
        bottom: 8px;
        width: 100%;
        text-align: center;
    }

    /* Number text (1/3 etc) */
    .numbertext {
        color: #f2f2f2;
        font-size: 12px;
        padding: 8px 12px;
        position: absolute;
        top: 0;
    }

    /* The dots/bullets/indicators */
    .dot {
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
    }

    .active {
        background-color: #717171;
    }

    /* Fading animation */
    .fade {
        -webkit-animation-name: fade;
        -webkit-animation-duration: 1.5s;
        animation-name: fade;
        animation-duration: 1.5s;
    }

    @-webkit-keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
    }

    @keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
    }

    /* On smaller screens, decrease text size */
    @media only screen and (max-width: 300px) {
        .text {font-size: 11px}
    }
    </style>
</head>

<body>

<div class="container-fluid">
<div id="edit-annonce" class="content scaffold-edit" role="main">
    <h1>Modification</h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.annonce}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.annonce}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <%--<g:uploadForm controller="annonce" action="update" id="${annonce.id}">
        <g:hiddenField name="version" value="${this.annonce?.version}"/>
        <fieldset class="form">
            <div class="fieldcontain required">
                <label for="title">Title
                    <span class="required-indicator">*</span>
                </label>
                <input type="text" name="title" value="${annonce.title}" required="" id="title">
            </div>

            <div class="fieldcontain required">
                <label for="description">Description
                    <span class="required-indicator">*</span>
                </label>
                <input type="text" name="description" value="${annonce.description}" required=""
                               id="description">
            </div>

            <div class="fieldcontain required">
                <label for="price">Price
                    <span class="required-indicator">*</span>
                </label><input type="number decimal" name="price" value="${annonce.price}" required="" min="0.0" id="price">
            </div>

            <div class="fieldcontain">
                <label for="illustrations">Illustrations</label>
                <g:each in="${annonce.illustrations}" var="illustration">
                    <img src="${baseUrl + illustration.filename}" />
                </g:each>
            </div>

            <div class="fieldcontain">
                <label for="file">Upload</label>
                <input style="display: inline" type="file" name="file" id="file"/>
            </div>

            <div class="fieldcontain required">
                <label for="author">Author
                    <span class="required-indicator">*</span>
                </label>
                <g:select name="author.id" from="${userList}" optionKey="id" optionValue="username" />
            </div>
        </fieldset>
        <fieldset class="buttons">
            <input class="save" type="submit"
                   value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:uploadForm>--%>
    <div class="container">

        <div class="row">
            <div class="col-md-4 order-md-2 mb-4">

            </div>

            <div class="col-md-12">
                <g:uploadForm class="form-signin" enctype="multipart/form-data" action="update" id="${annonce.id}" method="POST"
                        style="max-width:30rem !important;">
                    <br>

                    <div class="form-label-group">
                        <label class="m-0 font-weight-bold text-primary" for="title">Titre</label>
                        <input type="text" name="title" value="${this.annonce.title}" required="" id="title"
                               class="form-control"
                               autofocus="">
                    </div>
                    <br>

                    <div class="form-label-group">
                        <label class="m-0 font-weight-bold text-primary" for="description">Description</label>
                        <input type="text" name="description" value="${this.annonce.description}"
                               required="" id="description" class="form-control">

                    </div>
                    <br>

                    <div class="form-label-group">
                        <label class="m-0 font-weight-bold text-primary">Prix</label>
                        <input type="number" step="0.01" name="price" required="" min="0.0" id="price"
                               class="form-control" value="${this.annonce.price}">
                    </div>
                    <br>

                        <!-- Illustrations -->
                        <div class="card shadow lg-12">
                            <div class="card-header py-12">
                                <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
                            </div>
                            <div class="slideshow-container">

                                <g:each var="illustration" in = "${this.annonce.illustrations}">
                                    <div class="mySlides">
                                        <asset:image src="${illustration.filename}" class="illustrationmodif" height="300px" alt="Annonces" />
                                        <a onclick="getConfirmation(${illustration.id})">
                                            <div class="delete"><span class="fa fa-trash" data-toggle="tooltip" data-original-title="Supprimer"></span></div>
                                        </a>
                                    </div>
                                </g:each>
                                <div class="text-center d-none d-md-inline">
                                    <g:link class="rounded-circle border-0" onclick="plusSlides(-1)"><</g:link>
                                    <g:link class="rounded-circle border-0" onclick="plusSlides(1)">></g:link>
                                </div>
                            </div>

                        </div>
                    <br>
                    <div class="form-label-group">
                        <label class="m-0 font-weight-bold text-primary" for="file">Autres : </label>
                        <input style="display: inline" type="file" name="file" id="file"/>
                    </div>
                    <br>
                    <div class="form-label-group">
                        <input class="btn btn-primary btn-warning btn-lg btn-block" type="submit"
                               value="Modifier"/>

                    </div>
                </g:uploadForm>
                <br><br><br><br><br><br><br>
            </div>
        </div>

    </div>
</div>
</div>
<script>
    var i = 0;

    function add() {
        i++;
    }

    function add_fields() {
        document.getElementById('wrapper').innerHTML += '<input type="file" name="filename' + i + '" value="" required="" id="filename" placeholder="Entrez nom de fichier"> <br>\r\n';
    }
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }
    showSlides();

    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) {slideIndex = 1}
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
        setTimeout(showSlides, 5000); // Change image every 5 seconds
    }
</script>

</body>
</html>

grails-app/views/annonce/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'annonce.label', default: 'Annonce')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<div class="container-fluid">

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item">
            <h1 class="h1 mb-0 text-gray-800" style="font-weight: bold">Annonce

            </h1>

        <li class="breadcrumb-item">
                <i class="fas fa-angle-right header-action" style="font-weight: bold;margin-top: 20px"></i>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="annonce">
                <button  type="button" class="btn btn-success header-action"> <i class="fa fa-columns" aria-hidden="true"></i> Liste</button>
            </g:link>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="annonce" action="create">
                <button type="button" class="btn btn-primary header-action"><i class="fa fa-plus" aria-hidden="true"></i> Création</button>
            </g:link>
        </li>
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="index" method = "get">
            <div class="input-group header-action">
                <input class="form-control" type="text"  placeholder="Titre"  id="title"  value = "${title}" name="title" aria-label="Search" aria-describedby="basic-addon2" />
                <input class="form-control" type="text"  placeholder="Prix"  id="price"  value = "${price}" name="price" aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
    </ol>
</div>
<div class="container-fluid">
    <g:each var="annonce" in = "${annonceList}" status="i">
        <div class="row row_annonce">
            <!-- Earnings (Monthly) Card Example -->
            <div class="col-md-10" style="margin-left: 100px">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-8 block_contenu">
                                <div class="text-xs font-weight-bold text-primary  mb-1">
                                    <g:link id = "${annonce.id}" action="show" controller="annonce">
                                        <div class="titre col-mr-7">
                                            <h3>${annonce.title}</h3>
                                        </div>
                                    </g:link>
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Description : <i class="valeur_annonce">${annonce.description}</i></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Prix : <i class="valeur_annonce"><g:formatNumber number="${annonce.price}" format="###,##0.##" />$</i></div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Crée le :
                                    <i class="valeur_annonce">
                                        <g:formatDate format="dd MMMM yyyy" date="${annonce.dateCreated}"/> à
                                        <g:formatDate type="time" style="SHORT" date="${annonce.dateCreated}"/>
                                    </i></div>
                            </div>
                            <div class="col mr-2">

                                        <asset:image src="${annonce.illustrations[0].filename}" height="144px" class="illustrations" />
                            </div>
                        </div>
                        <div class="action">
                            <g:link id = "${annonce.id}" action="edit" controller="annonce">
                                <div class="edit">
                                    <span class="fa fa-edit" data-toggle="tooltip" data-original-title="Modifier"></span>
                                </div>
                            </g:link>
                            <g:link id = "${annonce.id}" action="show" controller="annonce">
                                <div class="detail">
                                    <span class="fa fa-eye" data-toggle="tooltip" data-original-title="Détail"></span>
                                </div>
                            </g:link>
                            <a onclick="getConfirmation(${annonce.id})">
                                <div class="delete"><span class="fa fa-trash" data-toggle="tooltip" data-original-title="Supprimer"></span></div>
                            </a>

                        </div>

                    </div>
                </div>
            </div>
        </div>
        <hr class="sidebar-divider my-0">
    </g:each>
</div>
<div class="mypagination">
    <p class="result">Résultat par page</p>
    <select onchange="pagination(this.value)" name="nbPage" id="nbPage" class ="nbParPage">
        <g:each var="lm" in="${listMax}" status="i">
            <g:if test="${lm == max}">
                <option selected value="${lm}">${lm}</option>
            </g:if>
            <g:else>
                <option value="${lm}">${lm}</option>
            </g:else>
        </g:each>
    </select>
    <g:paginate total="${countList ?: 0}" prev="&lt;" next="&gt;"/>

</div>

</body>
</html>