grails-app/domain/com/mbds/grails/User.groovy
package com.mbds.grails

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import grails.compiler.GrailsCompileStatic

@GrailsCompileStatic
@EqualsAndHashCode(includes='username')
@ToString(includes='username', includeNames=true, includePackage=false)
class User implements Serializable {

    private static final long serialVersionUID = 1

    String username
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [annonces: Annonce]

    Set<Role> getAuthorities() {
        (UserRole.findAllByUser(this) as List<UserRole>)*.role as Set<Role>
    }

    static constraints = {
        password nullable: false, blank: false, password: true
        username nullable: false, blank: false, unique: true
    }

    static mapping = {
	    password column: '`password`'
    }
}

grails-app/controllers/com/mbds/grails/UserController.groovy
package com.mbds.grails

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*


class UserController {

    UserService userService
    UserRoleService userRoleService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond userService.list(params), model: [userCount: userService.count(), username: params.username]
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def show(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def create() {
        respond new User(params)
    }

    @Secured('ROLE_ADMIN')
    def save(User user) {
        if (user == null) {
            notFound()
            return
        }
        println "FOUN"
        try {
            userService.save(user)
        } catch (ValidationException e) {
            println "ERROR FIELD"
            respond user.errors, view: 'create'
            return
        }
        println "ERROR"
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: CREATED] }
        }
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def edit(Long id) {
        respond userService.get(id)
    }

    @Secured('ROLE_ADMIN')
    def update(User user) {
        if (user == null) {
            notFound()
            return
        }

        try {
            userService.save(user)
        } catch (ValidationException e) {
            respond user.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), user.id])
                redirect user
            }
            '*' { respond user, [status: OK] }
        }
    }

    @Secured('ROLE_ADMIN')
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }
        try {
            def user = User.findById(id)
            if (user) {
                println user.username

                def delete = UserRole.removeAll(user)
                println delete
                if (delete != 0) {
                    userService.delete(id)
                }
            }
            render("success")
        }
        catch (ValidationException e) {
            render('echec')
        }
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    @Secured(['ROLE_ADMIN', 'ROLE_MODO'])
    def register() {

        if (!params.password.equals(params.repassword)) {
            flash.message = "Le mot de passe et la confirmation mot de passe ne correspondent pas"
            if (params.id) {
                redirect(action: "edit", id: params.id)
            } else {
                redirect action: "create"
            }

            return
        } else {
            try {
                def user = null
                def role = null
                if (!params.id) {
                        user = new User(username: params.username, password: params.password)
                        userService.save(user)
                    role = Role.get(params.role.id)
                } else {
                    user = userService.get(params.id)
                    println user.username
                    user.username = params.username
                    user.password = params.password
                    role = Role.get(params.role.id)

                }

                if (user && role) {
                    if (!params.id) {
                        UserRole.create user, role
                    } else {
                        userService.save(user)
                        UserRole.removeAll(user)
                        UserRole.create user, role
                    }


                    UserRole.withSession {
                        it.flush()
                        it.clear()
                    }

                    flash.message = "Utilisateur enregistré avec succès."
                    redirect controller: "user", action: "index"
                } else {
                    flash.message = "Veuillez vérifier les champs"
                    if (params.id) {
                        redirect(action: "edit", id: params.id)
                    } else {
                        redirect action: "create"
                    }
                    return
                }
            } catch (ValidationException e) {
                flash.message = "Une erreur s'est produite"
                if (params.id) {
                    redirect(action: "edit", id: params.id)
                } else {
                    redirect action: "create"
                }
                return
            }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
    <title><g:message code="default.list.label" args="[entityName]" /></title>
</head>
<body>
<div class="container-fluid">

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item">
            <h1 class="h1 mb-0 text-gray-800" style="font-weight: bold">Utilisateur

            </h1>

        <li class="breadcrumb-item">
            <i class="fas fa-angle-right header-action" style="font-weight: bold;margin-top: 20px"></i>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="user">
                <button  type="button" class="btn btn-success header-action"> <i class="fa fa-columns" aria-hidden="true"></i> Liste</button>
            </g:link>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="user" action="create">
                <button type="button" class="btn btn-primary header-action"><i class="fa fa-plus" aria-hidden="true"></i> Création</button>
            </g:link>
        </li>
    </ol>
</div>
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-10 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">Création</h5>
                <g:if test='${flash.message}'>
                    <div class="alert alert-danger" role="alert">${flash.message}</div>
                </g:if>
                <form class="form-signin" action="register" method="POST" id="loginForm" autocomplete="off">
                    <div class="form-group">
                        <label for="role">Role</label>
                        <g:select class="form-control" name="role.id"
                                  from="${com.mbds.grails.Role.list()}"
                                  optionValue="authority"
                                  optionKey="id" />
                    </div>

                    <div class="form-group">
                        <label for="username">Identifiant</label>
                        <input type="text" placeholder="Identifiant" class="form-control" name="username" id="username" autocapitalize="none"/>
                    </div>

                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" placeholder="Mot de passe" class="form-control" name="password" id="password"/>
                    </div>

                    <div class="form-group">
                        <label for="password">Confirmation mot de passe</label>
                        <input type="password" placeholder="Confirmation" class="form-control" name="repassword" id="repassword"/>
                    </div>
                    <button id="submit" class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Enregistrer</button>
                    <hr class="my-4">
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(event) {
        document.forms['loginForm'].elements['username'].focus();
    });
</script>
</body>
</html>

grails-app/views/user/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="container-fluid">

    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item">
            <h1 class="h1 mb-0 text-gray-800" style="font-weight: bold">Utilisateur

            </h1>

        <li class="breadcrumb-item">
            <i class="fas fa-angle-right header-action" style="font-weight: bold;margin-top: 20px"></i>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="user">
                <button type="button" class="btn btn-success header-action"><i class="fa fa-columns"
                                                                               aria-hidden="true"></i> Liste
                </button>
            </g:link>
        </li>
        <li class="breadcrumb-item">
            <g:link controller="user" action="create">
                <button type="button" class="btn btn-primary header-action"><i class="fa fa-plus"
                                                                               aria-hidden="true"></i> Création</button>
            </g:link>
        </li>
    </ol>
</div>

<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-10 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">Modification</h5>
                <g:if test='${flash.message}'>
                    <div class="alert alert-danger" role="alert">${flash.message}</div>
                </g:if>
                <g:form resource="${this.user}" action="register" method="PUT" class="form-signin">
                    <input type="hidden" placeholder="Identifiant" class="form-control" name="id" id="id"
                           autocapitalize="none" value="${this.user.id}"/>
                    <div class="form-group">
                        <label for="role">Role</label>
                        <g:select class="form-control" name="role.id"
                                  from="${com.mbds.grails.Role.list()}"
                                  optionValue="authority"
                                  optionKey="id" value="${this.user.authorities[0].id}" />
                    </div>

                    <div class="form-group">
                        <label for="username">Identifiant</label>
                        <input type="text" placeholder="Identifiant" class="form-control" name="username" id="username"
                               autocapitalize="none" value="${this.user.username}"/>
                    </div>

                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" placeholder="Mot de passe" class="form-control" name="password"
                               id="password"/>
                    </div>

                    <div class="form-group">
                        <label for="password">Confirmation mot de passe</label>
                        <input type="password" placeholder="Confirmation" class="form-control" name="repassword"
                               id="repassword"/>
                    </div>
                    <button id="submit" class="btn btn-lg btn-primary btn-block text-uppercase"
                            type="submit">Enregistrer</button>
                    <hr class="my-4">
                </g:form>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
    <div class="container-fluid">

        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item">
                <h1 class="h1 mb-0 text-gray-800" style="font-weight: bold">Utilisateur

                </h1>

            <li class="breadcrumb-item">
                <i class="fas fa-angle-right header-action" style="font-weight: bold;margin-top: 20px"></i>
            </li>
            <li class="breadcrumb-item">
                <g:link controller="user">
                    <button  type="button" class="btn btn-success header-action"> <i class="fa fa-columns" aria-hidden="true"></i> Liste</button>
                </g:link>
            </li>
            <li class="breadcrumb-item">
                <g:link controller="user" action="create">
                    <button type="button" class="btn btn-primary header-action"><i class="fa fa-plus" aria-hidden="true"></i> Création</button>
                </g:link>
            </li>
        </ol>
    </div>
    <div class="col-md-10" style="margin-left: 100px">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Identifiant</th>
            <th scope="col">Role</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <g:each in="${userList}" var="user">
        <tr>
            <td>${user.username}</td>
            <td>${user.authorities.authority[0]}</td>
            <td>
            <g:link id = "${user.id}" action="edit" controller="user" class="btn btn-info btn-circle btn-sm" >
                <i class="fas fa-pencil-alt"></i>
            </g:link>
                <a href="#" onclick="getConfirmationDeleteUser(${user.id})" class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash"></i></a></td>
        </tr>
        </g:each>
        </tbody>
    </table>
                <g:paginate next="Suivant" prev="Précédent"
                            maxsteps="0" controller="user"
                            action="index" total="${userCount}" />
            </div>
        </div>
    </div>
    </body>
</html>

grails-app/views/user/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-user" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="user" />
            <g:form resource="${this.user}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.user}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>